export enum DisplayType {
  CHAT = "SHOW_CHAT",
  CLOSE_CHAT = "CLOSE_CHAT",
  HEADERS = "SHOW_HEADERS",
  CLOSE_HEADERS = "CLOSE_HEADERS",
  SHOW_SETTINGS = "SHOW_SETTINGS",
  CLOSE_SETTINGS = "CLOSE_SETTINGS",
  CLOSE_OVERLAY = "CLOSE_OVERLAY",
  DEFAULT_DISPLAY = "DEFAULT_DISPLAY",
}
