export enum MessageType {
  JOIN = "JOIN",
  LEAVE = "LEAVE",
  NEW_MESSAGE = "NEW_MESSAGE",
  NEW_PRIVATE_MESSAGE = "NEW_PRIVATE_MESSAGE",
  REQUEST_APPROVED = "REQUEST_APPROVED",
  NEW_FRIEND_REQUEST = "NEW_FRIEND_REQUEST",
  REQUEST_CANCELLED = "REQUEST_CANCELLED",
  FRIENDSHIP_DELETED = "FRIENDSHIP_DELETED",
}
